blank_issues_enabled: false
defaults::
  - template: "01-hotbug_report.yml"
    name: ğŸš¨ç·Šæ€¥ãƒã‚°å ±å‘Š
    about: ç·Šæ€¥ãªãƒã‚°ã‚’å ±å‘Šã™ã‚‹
  - template: "02-bug_report.md"
    name: ğŸãƒã‚°å ±å‘Š
    about: ãƒã‚°ã‚’å ±å‘Šã™ã‚‹
  - template: "03-feature_request.md"
    name: ğŸ’¡æ”¹å–„ãƒ»ãƒªãƒ•ã‚¡ã‚¯ã‚¿ãƒªãƒ³ã‚°
    about: æ–°æ©Ÿèƒ½ã®ã‚¢ã‚¤ãƒ‡ã‚¢ã‚’ææ¡ˆã™ã‚‹
